version: '3'

services:
  peikareh:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/peikareh
      - peikareh_static_volume:/peikare/static
    restart: always
    expose:
      - "8000"
    networks:
      - peikareh_network
      - nginx
    depends_on:
      - postgresql

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - peikareh
    image: nginx:latest
    networks:
      - nginx
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


  postgresql:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - peikareh_network

volumes:
  postgres:
  peikareh_static_volume:
networks:
  peikareh_network:
  nginx:

