version: '3'

services:
  peikareh:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/peikareh
      - peikareh_static_volume:/peikare/static
    restart: always
    ports:
      - "8000:8000"
    networks:
      - peikareh_network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - peikareh_network

volumes:
  postgres:
  peikareh_static_volume:
networks:
  peikareh_network:

