# Generated by Django 3.1.3 on 2020-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
