# Generated by Django 3.1.3 on 2021-02-01 20:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_title', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('image', models.ImageField(upload_to='articles_pic/%Y/%m/%d/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
