# Generated by Django 3.0.2 on 2020-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=400, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='products', to='shop.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
