# Generated by Django 3.1.3 on 2021-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products_pic/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('attribute', models.JSONField(blank=True, help_text='in this format: {"key" : "value", "key2" : "value2"}', null=True)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='products', to='shop.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
