# Generated by Django 3.1.3 on 2021-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_1',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_2',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_3',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_4',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_5',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_description',
            field=models.TextField(blank=True, help_text='used for seo', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_title',
            field=models.CharField(blank=True, help_text='used for seo', max_length=200, null=True),
        ),
    ]
