# Generated by Django 3.1.3 on 2020-11-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
